### ISSUE TITLE
关于webp的请教

### ISSUE THREAD

**Issue by LanCat** [wintercn/blog#11]
我抓包请求下来的 淘宝网站 都不是webp 还是jpg格式的图片？？现在淘宝项目不是用webp了吗，是全部是用webp还是只有一部分用webp？
![640587b2-478d-4cce-9818-c6844b9095b6](https://user-images.githubusercontent.com/17734684/28454275-29d06f8a-6e2d-11e7-9264-836703b20b2d.png)

**Comment by ChangHaiHe** [comment]
.

**Comment by wintercn** [comment]
淘宝是否使用webp是根据浏览器环境自动判断的。
